#!/usr/bin/env python3
"""Synchronize Fianchetto's active palette with supported desktop apps."""

from __future__ import annotations

import argparse
import colorsys
import hashlib
import os
from pathlib import Path
import re
import shutil
import subprocess


def colour(value: str) -> str:
    value = value.strip().lstrip("#")
    if len(value) == 8:  # QColor can serialize opaque colours as AARRGGBB.
        value = value[2:]
    if not re.fullmatch(r"[0-9a-fA-F]{6}", value):
        raise argparse.ArgumentTypeError(f"invalid colour: {value}")
    return value.lower()


def mix(first: str, second: str, amount: float) -> str:
    """Blend towards second, returning an RRGGBB value."""
    a = tuple(int(first[index:index + 2], 16) for index in (0, 2, 4))
    b = tuple(int(second[index:index + 2], 16) for index in (0, 2, 4))
    return "".join(f"{round(x + (y - x) * amount):02x}" for x, y in zip(a, b))


def soften(value: str, saturation: float = 0.88, max_lightness: float = 0.72) -> str:
    """Keep Material colours comfortable while preserving their identity."""
    red, green, blue = (int(value[index:index + 2], 16) / 255 for index in (0, 2, 4))
    hue, lightness, sat = colorsys.rgb_to_hls(red, green, blue)
    red, green, blue = colorsys.hls_to_rgb(hue, min(lightness, max_lightness), sat * saturation)
    return "".join(f"{round(channel * 255):02x}" for channel in (red, green, blue))


parser = argparse.ArgumentParser()
parser.add_argument("--scheme", required=True)
parser.add_argument("--force", action="store_true")
for name in ("background", "surface", "border", "text", "muted", "accent",
             "sky", "mint", "lilac", "peach", "rose", "butter", "red"):
    parser.add_argument(f"--{name}", required=True, type=colour)
for name in ("kitty", "fish", "hyprland", "spicetify", "neovim"):
    parser.add_argument(f"--{name}", choices=("0", "1"), default="0")
args = parser.parse_args()

home = Path.home()
config_home = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
state_home = Path(os.environ.get("XDG_STATE_HOME", home / ".local/state"))
state_dir = state_home / "fianchetto"
state_dir.mkdir(parents=True, exist_ok=True)
changed_apps: list[str] = []
notes: list[str] = []


def write_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
    return True


if args.kitty == "1":
    kitty_file = config_home / "kitty/fianchetto-theme.conf"
    if args.scheme == "fianchetto":
        kitty = """# Generated by Fianchetto. Do not edit.
foreground #dadada
background #0A1114
selection_foreground #dadada
selection_background #232a2d
cursor #b3b9b8
cursor_text_color #232a2d
color0 #141B1E
color1 #e57474
color2 #8ccf7e
color3 #e5c76b
color4 #67b0e8
color5 #c47fd5
color6 #6cbfbf
color7 #b3b9b8
color8 #2d3437
color9 #ef7e7e
color10 #96d988
color11 #f4d67a
color12 #71baf2
color13 #ce89df
color14 #67cbe7
color15 #bdc3c2
active_tab_foreground #e182e0
active_tab_background #1b2224
inactive_tab_foreground #cd69cc
inactive_tab_background #232a2c
"""
    else:
        kitty = f"""# Generated by Fianchetto. Do not edit.
background #{args.background}
foreground #{args.text}
cursor #{args.sky}
cursor_text_color #{args.background}
selection_background #{args.surface}
selection_foreground #{args.text}
url_color #{args.sky}
active_border_color #{args.sky}
inactive_border_color #{args.border}
color0 #{args.surface}
color1 #{args.red}
color2 #{args.mint}
color3 #{args.butter}
color4 #{args.sky}
color5 #{args.lilac}
color6 #{args.peach}
color7 #{args.text}
color8 #{args.border}
color9 #{args.rose}
color10 #{args.mint}
color11 #{args.butter}
color12 #{args.accent}
color13 #{args.lilac}
color14 #{args.peach}
color15 #{args.text}
"""
    if write_changed(kitty_file, kitty):
        changed_apps.append("Kitty")
        try:
            subprocess.run(["pkill", "-USR1", "kitty"], check=False,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except FileNotFoundError:
            pass
    kitty_conf = config_home / "kitty/kitty.conf"
    include = "include fianchetto-theme.conf"
    if kitty_conf.exists() and include not in kitty_conf.read_text(encoding="utf-8", errors="ignore"):
        notes.append("add 'include fianchetto-theme.conf' to kitty.conf")


if args.fish == "1":
    if not shutil.which("fish"):
        notes.append("Fish is not installed")
    else:
        # Install and select a real Fish theme. This reliably supersedes a
        # previously saved theme such as Dracula without modifying config.fish
        # or removing any of the user's existing theme files.
        fish_colours = {
            "fish_color_normal": args.text,
            "fish_color_command": args.sky,
            "fish_color_keyword": args.lilac,
            "fish_color_quote": args.butter,
            "fish_color_redirection": args.peach,
            "fish_color_end": args.rose,
            "fish_color_error": args.red,
            "fish_color_param": args.text,
            "fish_color_option": args.mint,
            "fish_color_comment": args.muted,
            "fish_color_selection": f"{args.text} --background={args.surface}",
            "fish_color_search_match": f"{args.text} --background={args.surface}",
            "fish_color_operator": args.peach,
            "fish_color_escape": args.rose,
            "fish_color_autosuggestion": args.muted,
            "fish_color_cwd": args.sky,
            "fish_color_cwd_root": args.red,
            # Fish overlays this role on ordinary argument highlighting. A
            # style-only value keeps the primary argument colour and restores
            # the visual valid-path indicator used by Fish's default themes.
            "fish_color_valid_path": "--underline",
            "fish_color_user": args.lilac,
            "fish_color_host": args.muted,
            "fish_color_cancel": args.red,
            "fish_pager_color_progress": args.sky,
            "fish_pager_color_prefix": args.text,
            "fish_pager_color_completion": args.text,
            "fish_pager_color_description": args.muted,
            "fish_pager_color_selected_background": f"--background={args.surface}",
        }
        fish_theme_body = "".join(
            f"{name} {value}\n" for name, value in fish_colours.items()
        )
        # Fish 4 can select a theme variant from terminal colour-mode
        # detection. Kitty may report that mode as "unknown", so provide the
        # same dark palette for both modes instead of silently loading no role.
        fish_theme = (
            "# Generated by Fianchetto. Do not edit.\n"
            "# name: 'Fianchetto'\n\n"
            "[dark]\n"
            f"# preferred_background: {args.background}\n"
            + fish_theme_body
            + "\n[unknown]\n"
            f"# preferred_background: {args.background}\n"
            + fish_theme_body
        )
        fish_theme_file = config_home / "fish/themes/Fianchetto.theme"
        signature_file = state_dir / "fish-theme.sha256"
        signature = hashlib.sha256(fish_theme.encode("utf-8")).hexdigest()
        previous = signature_file.read_text(encoding="utf-8").strip() \
            if signature_file.exists() else ""
        theme_changed = write_changed(fish_theme_file, fish_theme)
        if args.force or theme_changed or previous != signature:
            # Set the universal variables directly. fish_config can block in a
            # non-interactive process on some Fish/terminal combinations,
            # which previously prevented later integrations from running.
            fish_script = "; ".join(
                f"set -U {name} -- {value}" for name, value in fish_colours.items()
            )
            try:
                result = subprocess.run(
                    ["fish", "-c", fish_script], check=False, timeout=5,
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            except subprocess.TimeoutExpired:
                result = None
            if result is not None and result.returncode == 0:
                write_changed(signature_file, signature + "\n")
                changed_apps.append("Fish")
            else:
                notes.append("Fish colour update failed")


if args.hyprland == "1":
    hypr_file = config_home / "hypr/fianchetto-theme.conf"
    hypr = f"""# Generated by Fianchetto. Do not edit.
$fianchettoAccent = rgb({args.accent})
$fianchettoBorder = rgb({args.border})
$fianchettoBackground = rgb({args.background})

general {{
    col.active_border = rgba({args.accent}ff)
    col.inactive_border = rgba({args.border}ff)
}}

decoration {{
    shadow {{
        color = rgba({args.background}99)
    }}
}}
"""
    if write_changed(hypr_file, hypr):
        changed_apps.append("Hyprland")
        if shutil.which("hyprctl"):
            for key, value in (
                ("general:col.active_border", f"rgba({args.accent}ff)"),
                ("general:col.inactive_border", f"rgba({args.border}ff)"),
                ("decoration:shadow:color", f"rgba({args.background}99)"),
            ):
                subprocess.run(["hyprctl", "keyword", key, value], check=False,
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


if args.neovim == "1":
    neovim_file = config_home / "nvim/lua/config/fianchetto.lua"
    if args.scheme == "matugen":
        neovim = f'''-- Generated by Fianchetto. Do not edit.
return {{
  bg = "#{args.background}",
  panel = "#{args.surface}",
  section = "#{mix(args.surface, args.accent, 0.08)}",
  completion_bg = "#{mix(args.background, args.accent, 0.05)}",
  completion_selected = "#{args.accent}",
  border = "#{args.border}",
  separator = "#{mix(args.background, args.accent, 0.14)}",
  fg = "#{args.text}",
  soft_fg = "#{mix(args.text, args.muted, 0.32)}",
  muted = "#{args.muted}",
  red = "#{args.red}",
  green = "#{args.mint}",
  yellow = "#{args.butter}",
  blue = "#{args.sky}",
  accent = "#{args.accent}",
  purple = "#{args.lilac}",
  cyan = "#{args.sky}",
  orange = "#{args.peach}",
  line_nr = "#{args.border}",
  line_nr_dim = "#{mix(args.background, args.muted, 0.28)}",
  cursor_line_nr = "#{args.muted}",
  tree_root = "#{args.muted}",
  tree_directory = "#{args.accent}",
  tree_file = "#{mix(args.text, args.muted, 0.32)}",
  tree_indent = "#{args.border}",
  tree_expander = "#{args.muted}",
  tree_dim = "#{mix(args.background, args.muted, 0.48)}",
  cmp_border = "#{args.border}",
  buffer_muted = "#{args.muted}",
  buffer_visible = "#{mix(args.text, args.muted, 0.55)}",
  buffer_close = "#{args.border}",
  status_muted = "#{args.muted}",
}}
'''
        if write_changed(neovim_file, neovim):
            changed_apps.append("Neovim")
    elif neovim_file.exists():
        # Fixed Fianchetto and other non-Matugen schemes keep the user's
        # regular Night theme and hand-written highlight overrides.
        neovim_file.unlink()
        changed_apps.append("Neovim (Night restored)")


if args.spicetify == "1":
    signature_file = state_dir / "spicetify-theme.sha256"
    previously_applied = signature_file.read_text(encoding="utf-8").strip() \
        if signature_file.exists() else ""

    # The stock Fianchetto palette has its own complete Spicetify theme.
    # Generated/imported palettes continue to use the generic Text theme.
    if args.scheme == "fianchetto":
        theme_dir = config_home / "spicetify/Themes/FianchettoText"
        signature = hashlib.sha256(b"theme:FianchettoText").hexdigest()
        if not theme_dir.is_dir():
            notes.append("Spicetify FianchettoText theme not found")
        elif shutil.which("spicetify"):
            colour_file = theme_dir / "color.ini"
            base_scheme = ""
            if colour_file.exists():
                schemes = re.findall(r"(?m)^\[([^]]+)\]", colour_file.read_text(encoding="utf-8"))
                base_scheme = next((name for name in schemes if name != "FianchettoDynamic"), "")
            command = ["spicetify", "config", "current_theme", "FianchettoText"]
            if base_scheme:
                command += ["color_scheme", base_scheme]
            subprocess.run(command,
                           check=False, stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL)
            if args.force or previously_applied != signature:
                subprocess.Popen(["spicetify", "apply"], stdout=subprocess.DEVNULL,
                                 stderr=subprocess.DEVNULL, start_new_session=True)
                write_changed(signature_file, signature + "\n")
                changed_apps.append("Spicetify")
    else:
        colour_file = config_home / "spicetify/Themes/FianchettoText/color.ini"
        if not colour_file.exists():
            notes.append("Spicetify FianchettoText color.ini not found")
        else:
            # Preserve FianchettoText's dark, low-contrast surfaces while using
            # the brighter generated role for interactive elements. The shell
            # already balances these foreground roles against its background;
            # aggressively desaturating them here makes the whole desktop look
            # grey and can make small Spotify controls hard to distinguish.
            calm_background = mix(args.background, "0a1114", 0.35)
            calm_surface = mix(calm_background, args.accent, 0.07)
            calm_border = mix(calm_background, args.accent, 0.18)
            calm_text = mix(args.text, "dadada", 0.45)
            calm_muted = mix(args.muted, calm_text, 0.38)
            calm_accent = soften(args.accent)
            calm_active = soften(args.accent, saturation=1.0, max_lightness=0.78)
            calm_red = soften(args.red, saturation=0.90, max_lightness=0.72)
            # FianchettoText's CSS consumes these custom roles. Using the
            # generic Spicetify role names here caused missing variables to
            # fall back to bright defaults (notably the white borders).
            section = f"""[FianchettoDynamic]
accent             = {calm_accent}
accent-active      = {calm_active}
accent-inactive    = {calm_surface}
banner             = {calm_accent}
border-active      = {calm_accent}
border-inactive    = {calm_border}
header             = {calm_muted}
highlight          = {calm_surface}
main               = {calm_background}
notification       = {calm_accent}
notification-error = {calm_red}
subtext            = {calm_muted}
text               = {calm_text}
"""
            section = section.rstrip() + "\n"
            original = colour_file.read_text(encoding="utf-8")
            pattern = re.compile(r"(?ms)^\[FianchettoDynamic\]\n.*?(?=^\[|\Z)")
            updated = pattern.sub(section, original) if pattern.search(original) \
                else original.rstrip() + "\n\n" + section
            signature = hashlib.sha256(("theme:FianchettoText\n" + section).encode("utf-8")).hexdigest()
            if updated != original:
                backup = colour_file.with_suffix(".ini.fianchetto-backup")
                if not backup.exists():
                    shutil.copy2(colour_file, backup)
                write_changed(colour_file, updated)
            if shutil.which("spicetify"):
                subprocess.run(["spicetify", "config", "current_theme", "FianchettoText",
                                "color_scheme", "FianchettoDynamic"], check=False,
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                # Wallpaper changes can happen rapidly. Rewriting color.ini is
                # enough for the next Spotify launch; `spicetify apply` also
                # restarts Spotify, so only do that for an explicit Apply now
                # request while Matugen is active.
                should_apply = args.force or args.scheme != "matugen"
                if should_apply and (args.force or updated != original
                                     or previously_applied != signature):
                    subprocess.Popen(["spicetify", "apply"], stdout=subprocess.DEVNULL,
                                     stderr=subprocess.DEVNULL, start_new_session=True)
                    write_changed(signature_file, signature + "\n")
                    changed_apps.append("Spicetify")
                elif updated != original:
                    changed_apps.append("Spicetify palette")


message = "Updated " + ", ".join(changed_apps) if changed_apps else "Application themes already current"
if notes:
    message += " · " + "; ".join(notes)
print(message)
