#!/usr/bin/env python3
"""Synchronize Fianchetto's active palette with supported desktop apps."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import re
import shutil
import subprocess


def colour(value: str) -> str:
    value = value.strip().lstrip("#")
    if len(value) == 8:  # QColor can serialize opaque colours as AARRGGBB.
        value = value[2:]
    if not re.fullmatch(r"[0-9a-fA-F]{6}", value):
        raise argparse.ArgumentTypeError(f"invalid colour: {value}")
    return value.lower()


parser = argparse.ArgumentParser()
parser.add_argument("--scheme", required=True)
for name in ("background", "surface", "border", "text", "muted", "accent", "red"):
    parser.add_argument(f"--{name}", required=True, type=colour)
for name in ("kitty", "hyprland", "spicetify"):
    parser.add_argument(f"--{name}", choices=("0", "1"), default="0")
args = parser.parse_args()

home = Path.home()
config_home = Path(os.environ.get("XDG_CONFIG_HOME", home / ".config"))
state_home = Path(os.environ.get("XDG_STATE_HOME", home / ".local/state"))
state_dir = state_home / "fianchetto"
state_dir.mkdir(parents=True, exist_ok=True)
changed_apps: list[str] = []
notes: list[str] = []


def write_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)
    return True


if args.kitty == "1":
    kitty_file = config_home / "kitty/fianchetto-theme.conf"
    if args.scheme == "fianchetto":
        kitty = """# Generated by Fianchetto. Do not edit.
foreground #dadada
background #0A1114
selection_foreground #dadada
selection_background #232a2d
cursor #b3b9b8
cursor_text_color #232a2d
color0 #141B1E
color1 #e57474
color2 #8ccf7e
color3 #e5c76b
color4 #67b0e8
color5 #c47fd5
color6 #6cbfbf
color7 #b3b9b8
color8 #2d3437
color9 #ef7e7e
color10 #96d988
color11 #f4d67a
color12 #71baf2
color13 #ce89df
color14 #67cbe7
color15 #bdc3c2
active_tab_foreground #e182e0
active_tab_background #1b2224
inactive_tab_foreground #cd69cc
inactive_tab_background #232a2c
"""
    else:
        kitty = f"""# Generated by Fianchetto. Do not edit.
background #{args.background}
foreground #{args.text}
cursor #{args.accent}
cursor_text_color #{args.background}
selection_background #{args.accent}
selection_foreground #{args.background}
url_color #{args.accent}
active_border_color #{args.accent}
inactive_border_color #{args.border}
color0 #{args.background}
color1 #{args.red}
color2 #{args.accent}
color3 #{args.muted}
color4 #{args.accent}
color5 #{args.muted}
color6 #{args.accent}
color7 #{args.text}
color8 #{args.border}
color9 #{args.red}
color10 #{args.accent}
color11 #{args.text}
color12 #{args.accent}
color13 #{args.muted}
color14 #{args.accent}
color15 #{args.text}
"""
    if write_changed(kitty_file, kitty):
        changed_apps.append("Kitty")
        try:
            subprocess.run(["pkill", "-USR1", "kitty"], check=False,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except FileNotFoundError:
            pass
    kitty_conf = config_home / "kitty/kitty.conf"
    include = "include fianchetto-theme.conf"
    if kitty_conf.exists() and include not in kitty_conf.read_text(encoding="utf-8", errors="ignore"):
        notes.append("add 'include fianchetto-theme.conf' to kitty.conf")


if args.hyprland == "1":
    hypr_file = config_home / "hypr/fianchetto-theme.conf"
    hypr = f"""# Generated by Fianchetto. Do not edit.
$fianchettoAccent = rgb({args.accent})
$fianchettoBorder = rgb({args.border})
$fianchettoBackground = rgb({args.background})

general {{
    col.active_border = rgba({args.accent}ff)
    col.inactive_border = rgba({args.border}ff)
}}

decoration {{
    shadow {{
        color = rgba({args.background}99)
    }}
}}
"""
    if write_changed(hypr_file, hypr):
        changed_apps.append("Hyprland")
        if shutil.which("hyprctl"):
            for key, value in (
                ("general:col.active_border", f"rgba({args.accent}ff)"),
                ("general:col.inactive_border", f"rgba({args.border}ff)"),
                ("decoration:shadow:color", f"rgba({args.background}99)"),
            ):
                subprocess.run(["hyprctl", "keyword", key, value], check=False,
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


if args.spicetify == "1":
    signature_file = state_dir / "spicetify-theme.sha256"
    previously_applied = signature_file.read_text(encoding="utf-8").strip() \
        if signature_file.exists() else ""

    # The stock Fianchetto palette has its own complete Spicetify theme.
    # Generated/imported palettes continue to use the generic Text theme.
    if args.scheme == "fianchetto":
        theme_dir = config_home / "spicetify/Themes/FianchettoText"
        signature = hashlib.sha256(b"theme:FianchettoText").hexdigest()
        if not theme_dir.is_dir():
            notes.append("Spicetify FianchettoText theme not found")
        elif shutil.which("spicetify"):
            subprocess.run(["spicetify", "config", "current_theme", "FianchettoText"],
                           check=False, stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL)
            if previously_applied != signature:
                subprocess.Popen(["spicetify", "apply"], stdout=subprocess.DEVNULL,
                                 stderr=subprocess.DEVNULL, start_new_session=True)
                write_changed(signature_file, signature + "\n")
                changed_apps.append("Spicetify")
    else:
        candidates = [
            config_home / "spicetify/Themes/text/color.ini",
            config_home / "spicetify/Themes/Text/color.ini",
        ]
        colour_file = next((path for path in candidates if path.exists()), None)
        if colour_file is None:
            notes.append("Spicetify Text color.ini not found")
        else:
            section = f"""[Fianchetto]
text               = {args.text}
subtext            = {args.muted}
main               = {args.background}
sidebar            = {args.background}
player             = {args.surface}
card               = {args.surface}
shadow             = {args.background}
selected-row       = {args.border}
button             = {args.accent}
button-active      = {args.accent}
button-disabled    = {args.border}
tab-active         = {args.surface}
notification       = {args.surface}
notification-error = {args.red}
misc               = {args.border}
"""
            section = section.rstrip() + "\n"
            original = colour_file.read_text(encoding="utf-8")
            pattern = re.compile(r"(?ms)^\[Fianchetto\]\n.*?(?=^\[|\Z)")
            updated = pattern.sub(section, original) if pattern.search(original) \
                else original.rstrip() + "\n\n" + section
            signature = hashlib.sha256(("theme:text\n" + section).encode("utf-8")).hexdigest()
            if updated != original:
                backup = colour_file.with_suffix(".ini.fianchetto-backup")
                if not backup.exists():
                    shutil.copy2(colour_file, backup)
                write_changed(colour_file, updated)
            if shutil.which("spicetify"):
                subprocess.run(["spicetify", "config", "current_theme", "text",
                                "color_scheme", "Fianchetto"], check=False,
                               stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                if updated != original or previously_applied != signature:
                    subprocess.Popen(["spicetify", "apply"], stdout=subprocess.DEVNULL,
                                     stderr=subprocess.DEVNULL, start_new_session=True)
                    write_changed(signature_file, signature + "\n")
                    changed_apps.append("Spicetify")


message = "Updated " + ", ".join(changed_apps) if changed_apps else "Application themes already current"
if notes:
    message += " · " + "; ".join(notes)
print(message)
